name: tickex_workspace

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test